siteTitle = "Daily Picks of Irene"
siteDescr = "Simply a way to get me online and be useful"
siteAuthor = "Ivana Irene Thomas"

siteGithubUrl = "http://github.com/ivanaairenee"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
